[zh-cn]
languageName = "Chinese (Simplified)"
languagedirection = "ltr"
title = "iHsin的站点"
weight = 1

[en]
languageName = "English"
languagedirection = "ltr"
title = "iHsin's Site"
weight = 2


